"""Provider-neutral response and client interface.

All concrete LLM clients in Release 01 return ``LLMResponse`` and implement
``BaseLLMClient.invoke``. This keeps notebooks independent from provider-specific
SDK response formats and makes it possible to switch between OpenAI, Ollama, and
OpenAI-compatible endpoints with the same calling pattern.
"""

from abc import ABC, abstractmethod
from typing import Any, Generic, TypeVar

from pydantic import BaseModel, Field

SchemaT = TypeVar("SchemaT", bound=BaseModel)


class StructuredLLMError(ValueError):
    """Raised when a provider cannot produce a validated structured response."""


class LLMResponse(BaseModel):
    """Normalized response returned by every provider wrapper.

    Attributes:
        content: Main text generated by the model. Notebooks should usually read
            this field instead of provider-specific response objects.
        model: Actual model name used for the call, for example
            ``"gpt-5.4-nano"`` or ``"qwen2.5:14b-instruct"``.
        provider: Provider wrapper that produced the response, such as
            ``"openai"``, ``"ollama"``, or ``"openrouter"``.
        latency_seconds: Approximate wall-clock duration of the request.
        usage: Token or evaluation counters when the provider returns them.
            Providers use different keys, so this remains a dictionary.
        raw: Original provider response serialized where practical. This is for
            debugging, not for normal notebook logic.
    """

    content: str
    model: str
    provider: str
    latency_seconds: float = Field(ge=0)
    usage: dict[str, Any] | None = None
    raw: Any | None = None


class StructuredLLMResponse(BaseModel, Generic[SchemaT]):
    """Normalized response returned by structured-output provider calls.

    Attributes:
        parsed: Typed Pydantic object produced by the provider's structured
            output path.
        content: Raw JSON/text content returned by the provider when available.
        model: Actual model name used for the call.
        provider: Provider wrapper that produced the response.
        latency_seconds: Approximate wall-clock duration of the request.
        usage: Token counters when available.
        raw: Original provider response serialized where practical.
    """

    parsed: SchemaT
    content: str
    model: str
    provider: str
    latency_seconds: float = Field(ge=0)
    usage: dict[str, Any] | None = None
    raw: Any | None = None


class BaseLLMClient(ABC):
    """Abstract interface implemented by every LLM provider client.

    A client stores the selected ``model``, provider name, and default
    temperature. Concrete subclasses decide how to authenticate and which HTTP or
    SDK endpoint to call, but callers always use ``invoke(system=..., user=...)``.
    """

    def __init__(self, model: str, provider: str, temperature: float = 0.2) -> None:
        """Initialize common identity and generation defaults.

        Args:
            model: Provider-specific model name to request.
            provider: Toolkit provider label used in ``LLMResponse.provider``.
            temperature: Default sampling temperature when a call does not
                override it.
        """
        self.model = model
        self.provider = provider
        self.temperature = temperature

    @abstractmethod
    def invoke(self, system: str, user: str, **kwargs: Any) -> LLMResponse:
        """Call the model with one system message and one user message.

        Args:
            system: Instruction layer that sets persona, behavior, and output
                constraints.
            user: Rendered user request, usually produced by a
                ``PromptTemplate``.
            **kwargs: Provider-specific options forwarded to the concrete SDK
                or HTTP endpoint. ``temperature`` is accepted by the toolkit,
                but concrete clients may omit it for models whose provider only
                supports the API default.

        Returns:
            Normalized ``LLMResponse``.
        """

    def invoke_structured(
        self,
        system: str,
        user: str,
        schema: type[SchemaT],
        **kwargs: Any,
    ) -> StructuredLLMResponse[SchemaT]:
        """Call the model and ask the provider to enforce a Pydantic schema.

        Providers that do not support native structured outputs should leave
        this method unsupported rather than simulating enforcement with prompt
        text and local parsing.
        """
        raise StructuredLLMError(
            f"Provider '{self.provider}' does not support native structured output."
        )
